### ISSUE TITLE
Error in package

### ISSUE THREAD

**Issue by regevbr** [bachya/py17track#69]
I'm using the home assistant integration which uses the latest version of this package. Recently I started to get the following error which causes the package to not work at all:

```
Error while setting up seventeentrack platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/seventeentrack/sensor.py", line 94, in async_setup_platform
    await data.async_update()
  File "/usr/src/homeassistant/homeassistant/components/seventeentrack/sensor.py", line 306, in _async_update
    self.summary = await self._client.profile.summary(
  File "/usr/local/lib/python3.9/site-packages/py17track/profile.py", line 111, in summary
    results[PACKAGE_STATUS_MAP[kind["e"]]] = kind["ec"]
KeyError: 5
```

I will try to provide more information later

**Comment by regevbr** [comment]
seems like my account has 2 new states 5 and 32, and the website is also unaware of them haha:
![image](https://user-images.githubusercontent.com/5775519/144726538-d71d6d45-3309-448d-8fe7-2217e3bf1a8a.png)
Seems like the best solution, for now, is to just add those 2 values to the PACKAGE_STATUS_MAP as `unknown` which I makes the issue go away.
